Repository cbnu-community/algorithm_skills, pull requests merged in 2020-09, with the labels that each got.

#7 난이도 카테고리 추가(#3)
  src/atoms/description.js
  src/data/advanced.js
  src/data/basic.js
  src/data/codingtest.js
Labels: enhancement

#11 난이도 카테고리 사용 여부를 선택하는 설정 추가(#9)
  src/atoms/description.js
  src/data/basic.js
Labels: enhancement

#27 탈자 수정(#26)
  src/data/basic.js
Labels: modification

#29 README.md 수정(#13)
  README.md
  blueprint.md
  generate-blueprint.js
  package.json
Labels: documentation

#30 캐시 처리부분 수정(#28)
  sw.js
Labels: modification

#31 캐시 처리부분 2/3차 수정(#28)
  sw.js
Labels: bug

#33 이름이 겹쳐서 중첩되던점 해결(#32)
  src/data/advanced.js
  src/data/basic.js
Labels: bug

#34 README.md 2차 수정(#13)
  README.md
Labels: documentation
